### ISSUE TITLE
Should unicode characters be allowed in the Hed schema?

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#1]
This decision will have implications both for expressiveness and for

**Comment by VisLab** [comment]
From Nima:
If HED is to be used across the world, I think we need to support UTF8 since /label, character/letter and alike could be in other languages and need to be provided in unicode (for example, when Chinese characters are displayed on screen they need to be put in HED somehow).

HED tools in MATLAB tools will have different levels of support for this, same with different version of MATLAB. Python tools (if in Python 3) should not have as much difficulty. I think we should remove unnecessary "right quotes" (//u2019) unicode chars from the schema though. 

Kay:
I agree

**Comment by VisLab** [comment]
The lines to be corrected for right quotes:

Line 593: ** Drop <nowiki>[For example something  drops from subject’s hand]</nowiki>
    Line 924: ** Clinic <nowiki> [Recording in a clinical setting such as in a hospital or doctor’s office]</nowiki>

**Comment by bigdelys** [comment]
The  "right quotes" have already been removed.

**Comment by happy5214** [comment]
The SI unit modifier "µ" has been added to the devunit branch, making Unicode a necessity.

**Comment by VisLab** [comment]
I think we are going to need to undo the addition of the "µ" and only allow ASCII.  The BIDS people have finally agreed the u is the preferred designation for micro.

**Comment by VisLab** [comment]
Only an explicit list of unicode characters is allowed.  This short list is to help with compliance with BIDS.
