### ISSUE TITLE
Attributes in VR worlds

### ISSUE THREAD

**Issue by touryan** [hed-standard/hed-specification#11]
In VR tasks we tend to record/mark objects in world coordinates (X,Y,Z) not screen coordinate. This is true for both static objects and moving objects (e.g. avatars). Consider adding 3D world coordinates under attributes (both static and as motion vectors).

**Comment by bigdelys** [comment]
I wonder whether it would be better to define "Virtual world coordinates" under "Attribute/Location" or to change "Real-world coordinates" there to just "coordinates" (and use virtual or real tags separately)...
I feel using "coordinates" provides better orthogonality. What do others think?

**Comment by dungscout96** [comment]
Changing "Real-world coordinates" to just "Coordinates" makes a lot of sense. Also should we consider removing "Room" (Attribute/Location/Real-world coordinates/Room)?
And we should specify unit for xyz

**Comment by VisLab** [comment]
Coordinate systems and VR will need to be addressed in a future VR library schema.  Anyone volunteer?
