### ISSUE TITLE
score eeg in hed

### ISSUE THREAD

**Issue by dorahermes** [hed-standard/hed-specification#137]
We are interested in creating a BIDS-events compatible HED library schema for the SCORE-EEG system according to the HED white paper and spec. @tpatpa started the work on this, and it would be good to have some input on questions about orthogonality vs maintaining the existing SCORE structure. Is this issue a good place to post questions and keep track of them and discuss?

**Comment by VisLab** [comment]
Yes this is a good place.  We'll start monitoring.  I will also share some documentation off line.

**Comment by VisLab** [comment]
The development process for library schema will be held in the hed-schema-library repository of the hed-standard organization github site. The development process for incorporating library schema into the hed-python tools and the hed-javascript tools is underway.

**Comment by dorahermes** [comment]
One issue that keeps coming up now during @tpatpa development of the SCORE HED schema library is that there are some attributes that overlap with attributes in the main HED Third Generation (e.g. 'Less-than'). When developing SCORE library schema's, is it correct to assume that HED always is 'present', such that a library schema is completely complementary?

**Comment by VisLab** [comment]
Yes there will always be a base HED schema and you should not duplicate the terms there.  You should be able to find most of the terms needed for basic descriptions of a lot of things.  Terms that are generally applicable that were missed can be added --- preferably for the official release of HED-3G, but I'm sure there will be some additional ones later.

The Library schema are completely complementary and the tools will treat HED strings containing terms from the base schema and multiple library schema seamlessly.

**Comment by dorahermes** [comment]
Great, thanks!

**Comment by tpatpa** [comment]
When developing, I am using the Process schema HED tool that converts HED vocabulary schema between .mediawiki and .xml format and checks that individual HED tags conform to the HED specification requirements and are not duplicated elsewhere in the schema.
Is it checking that tags in the schema library I am developing are not duplicated in the main HED schema?

**Comment by VisLab** [comment]
There is another button on that page to Check for 3G compliance.  That
checks for duplicate tags as well as tags that have invalid characters.

**Comment by VisLab** [comment]
There is more extensive wikimedia format checking that is in the works, but
isn't deployed yet.

**Comment by VisLab** [comment]
The SCORE library is now up.  Congratulations @tpatpa @dorahermes
