### ISSUE TITLE
XML format change to handle attributes

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#155]
There are two problems with the way we are handling attributes in the HED schema:  

1.  Attributes cannot have multiple values (`unitClass` and `relatedTag` attributes will have many multiples)
2.  The specification of the attributes in the `mediawiki` file does not translate into XML and is lost in the translation.

We could solve the first problem by lumping attributes into a single comma-separated string, but the second problem remains. The difficulty is going to become worse when people start developing library schema in JSON and writing a translator to XML.  

**The proposal:**

1.  Attributes should become elements and have their own section at the bottom of the schema.

```
<attributes>
   <attribute>
     <name>requireChild<name>
     <description>One of its descendants must be chosen to tag an event.</description>
   </attribute>
<attributes>
```
In the HED schema itself, the node:
 
```
<node>
      <name>Agent-property</name>
      <description>An attribute describing an agent</description>
      <node extensionAllowed="true" requireChild="true">
          <name>Cognitive-state</name>
         <description>The state of awareness of an agent.</description>
       </node>
</node>
```
becomes:

```
<node>
    <name>Agent-property</name>
    <description>An attribute describing an agent</description>
    <node>
        <name>Cognitive-state</name>
        <description>The state of awareness of an agent.</description>
        <extensionAllowed />
        <requireChild />
    </node>
</node>
```
My question is: what are the implications for the validator?  The older schema won't have this format.  However, it would not be hard to a convert schema tree that doesn't  have an <attributes></attributes> section into one that does as part of creating a schema object.

**Comment by dungscout96** [comment]
This is a necessary restructure. CTAGGER and the Schema Browser can be modified to accommodate the changes in Proposal 2. Since I saw the change from `<attributes>` in Proposal 1 to `<attributeDefinitions>` in Proposal 2 (was there a technical reason?), should unitClass definitions at the bottom of the schema be changed to `<unitClassDefinitions>` as well?

**Comment by VisLab** [comment]
The reason Proposal 1 isn't good is that the attribute name is a schema node name rather than the value of an Attribute element. 

In Proposal 2, the XSD doesn't change when we add additional attributes.  In Proposal 1, we have to change both the XML and the XSD --- which is definitely not what we want.  In Proposal 2, we should be able to develop the XSD once and not have to change it when additional attributes are added to the schema.

Yes we should revise the unitClass at the bottom as well.  The plan would be to write a translator of old XML to new XML format.

**Comment by VisLab** [comment]
We are close to finalizing the change in format.  (We need to get it over with before we get too far along with tool development.) Here is the proposed mediawiki format.  This should not affect much except the implementation of the conversion to XML which @IanCa is working on.  The advantages is that it allow us to include schema attributes in the XML so that they can be verified. It will also allow us to preserve the prologue and epiplogue that are present in some mediawiki files without interfering with any processing.  This format is described in more detail in Appendix B of the HED 3G Specification document. Please let me know if you foresee any difficulties with this (@IanCa, @happy5214, @dungscout96, @smakeig, @dorahermes, @tpatpa). 

> _header-line_
> _prologue_
> !# start hed
> _schema-specification_
> !# end schema
> _unit-class-specification_ ('''Unit classes''' )
> _unit-modifier-specification_ ('''Unit modifiers''' )
> _attribute-specification_ ('''Schema attributes''' )
> !# end hed 
> _epilogue_

The next comment has the proposed XML format.

**Comment by VisLab** [comment]
The proposed new HED XML format:

The XML format will be as follows:

````xml
<?xml version="1.0" ?>
<HED library="test" version="0.0.1">
<prologue>unique optional text blob</prologue>
<schema>
    …. schema specification ….
</schema>
<unitClasses> …</unitClasses>
<unitModifiers> … </unitModifiers>
<schemaAttributes> … </schemaAttributes>
<epilogue>unique optional text blob</epilogue>
</HED>
````

This format will allow us to preserve the prologue and epilogue information present in the mediawiki and to formally validate using an XSD. 

We will need to write both Python, Matlab, and JavaScript functions to translate from old format to new format. Tools would call those functions internally, so that all tools would use the new format.

 Please let me know if you foresee any difficulties with this (@IanCa, @happy5214, @dungscout96, @smakeig, @dorahermes, @tpatpa, @sappelhoff).

**Comment by VisLab** [comment]
**New XML format part 2:** The proposal is to use a mixed XML element for schema attributes with values.

The new node specification would be:

````xml
<node>
   <name>xxx</name>
   <description>yyy</description>
   <attribute> . . . </attribute>
   <attribute> . . . </attribute>
   <attribute> . . . </attribute>   
   <unitClass>www</unitClass>
   <unitClass>zzz</unitClass>
</node>
````
Schema attributes that are either present or absent (like `requireChild`) would be given as:

````xml
 <node>
<name>xxx</name>
<attribute>requireChild</attribute>
</node>
''''
Schema attributes that can have one or more values like `suggestedTag` would be given as:

````xml
<node>
<name>xxx</name>
<attribute>suggestedTag
<value>Sweet</value>
<value>Gustatory/Salty</value>
<value>Attribute/Sensory/Gustatory/Sour</value>
</attribute>
</node>
````

**Comment by dungscout96** [comment]
The mixed XML element would add a layer of complication for tools to parse. Since the XML is generated automatically from mediawiki, can we use the syntax
```
<attribute>
      <name>requireChild </name>
</attribute>
```
and
```
<attribute>
      <name>suggestedTag</name>
      <value>Sweet</value>
      <value>Gustatory/Salty</value>
      <value>Attribute/Sensory/Gustatory/Sour</value>
</attribute>
```
instead?

Also, aren't unit and attribute definition part of the schema as well or are we using "schema" to strictly refer to the vocabulary?

**Comment by happy5214** [comment]
> The mixed XML element would add a layer of complication for tools to parse. Since the XML is generated automatically from mediawiki, can we use the syntax
> 
> ```
> <attribute>
>       <name>requireChild </name>
> </attribute>
> ```
> 
> and
> 
> ```
> <attribute>
>       <name>suggestedTag</name>
>       <value>Sweet</value>
>       <value>Gustatory/Salty</value>
>       <value>Attribute/Sensory/Gustatory/Sour</value>
> </attribute>
> ```
> 
> instead?

Agreed.

**Comment by happy5214** [comment]
What are we allowing into the prologue and epilogue? Will they be sanitized to disallow XML syntax?

**Comment by VisLab** [comment]
Okay.... agreed we will use the <name> and not used mixed XML elements.  

The prologue and epilogue should be as sanitized as possible.  Does anyone have suggestions about standard sanitation libraries in Python and JavaScript.

What about unit classes?   Is the following okay in the schema part?

````xml
<unitClass>speed</unitClass>
````

Or should we use:

````xml
<unitClass>
    <name>speed</name>
</unitClass>
````

Also we are using the element <unitClass> in the <unitClasses> specification at the bottom outside of the schema specification. Is that okay to use the element for two different purposes?  Does anyone have a suggestion for a different name?

**Comment by VisLab** [comment]
Maybe `<unitType>`?

**Comment by happy5214** [comment]
Instead of renaming the element inside `<node>`, why don't we rename the schema-wide elements to match `<schemaAttributes>`, as such?
 
```xml
<?xml version="1.0" ?>
<HED library="test" version="0.0.1">
<prologue>unique optional text blob</prologue>
<schema>
    …. schema specification ….
</schema>
<schemaUnitClasses> …</schemaUnitClasses>
<schemaUnitModifiers> … </schemaUnitModifiers>
<schemaAttributes> … </schemaAttributes>
<epilogue>unique optional text blob</epilogue>
</HED>
```

**Comment by VisLab** [comment]
Agreed.  We can then go with:

````xml
<unitClass>speed</unitClass>
````

**Comment by VisLab** [comment]
To be consistent, I am proposing the following format for the .mediawiki:

_header-line:_ `HED` . . .
_prologue_
`!# start schema`
_schema-specification_
`!# end schema`
_unit-class-specification_
_unit-modifier-specification_
_attribute-specification_
`!# end hed `
_epilogue_

The tools would detect which version of the schema format being used by whether there is a `!# start hed ` (old version) or `!# start schema` (new version). This would allow us to release HED (2G) in the updated schema so we could include the prologue.  Please comment: @happy5214 @dungscout96 @IanCa

**Comment by VisLab** [comment]
Actually, I think once we get the converters done, I think all of the `.mediawik`i files will be converted to the new format.   We need to have a .`mediawiki `to `.xml` for the new version of XML and the old version.  The `.mediawiki` will always be the same going forward.  There are only two `.mediawiki` right now.  I am going to make two new versions of the .mediawiki one for each of HED 3G and HED 2G.  They will be called `HED-generation2-schema-v2.mediawiki`  and `HED-generation3-schema-v2.mediawiki`

**Comment by VisLab** [comment]
To avoid conflict with the unitClass definitions we will use unitType in the nodes to specify units. This is now reflected in Appendix B of the HED specification document.

````xml
<node>
   <name>xxx</name>
   <description>yyy</description>
   <attribute> . . . </attribute>
   <attribute> . . . </attribute>
   <attribute> . . . </attribute>   
   <unitType>www</unitType>
   <unitType>zzz</unitType>
</node>
```

**Comment by happy5214** [comment]
So we're not going with my idea in https://github.com/hed-standard/hed-specification/issues/155#issuecomment-778463456 of renaming the elements at the bottom instead?

**Comment by VisLab** [comment]
As I was working on the specification document, I realized that `<schemaUnitClasses>` and `<schemaUnitModifiers>` were problematic names. Those names imply that unitClass refers to the schema, but it doesn't. It refers to the data being tagged. In contrast `<schemaAttributes>`  makes sense because those attributes refer to the actual schema and are in contrast to the `Attribute` tag which refers to data.  I thought that it would be too confusing to users.  

The new proposal doesn't change the names of elements that are already in the schema.  The `unitClass` attribute becomes a `unitType` element. This isn't fixed in stone yet if you have additional thoughts.

**Comment by dungscout96** [comment]
I think instead of changing to `<unitType>`, we can change the one at the bottom outside the schema to `<unitClassDefinitions>`. This way `<unitClass>` attribute and `<unitClassDefinitions>` clearly correspond to each other. Then we can also have `<unitModifierDefinitions>` and `<schemaAttributeDefinitions>` for consistency.

**Comment by happy5214** [comment]
Frankly, using `unitType` for one and `unitClass` for the other is IMO incongruous and ugly. I'm OK with @dungscout96's idea, but I want to see a full template (with individual definition elements included).

**Comment by VisLab** [comment]
Okay, we'll go with Dung's proposal.  The full template is in [Appendix B](https://docs.google.com/document/d/1icp4fJyCqngSfYy1kPe7FJ-bqA8_Ei67oqn5--0vrDo/edit?usp=sharing) of the specification.

**Comment by VisLab** [comment]
For reference. Here is the finalized version of the new HED XML format. Starting with HED8.0.0-alpha.2, the HED XML files will have the format listed below.   Tools will still read XML files in the old format but will not be able to do full validation on them. Schema developers will be able to read the old format and write the new format to validate.

````xml
<?xml version="1.0" ?>
<HED library="test" version="0.0.1">
<prologue>unique optional text blob</prologue>
<schema>
<node>
   <name>xxx</name>
   <description>yyy</description>
   <attribute> . . . </attribute>
   <unitClass>...</unitClass>
</node>
</schema>
<unitClassDefinitions>
   <unitClassDefinition> … <unitClassDefinition>
</unitClassDefinitions>
<unitModifierDefinitions>
   <unitModifierDefinition> … <unitModifierDefinition>
</unitModifierDefinitions>
<schemaAttributeDefinitions> 
   <schemaAttributeDefinition> … <schemaAttributeDefinition>
</schemaAttributeDefinitions>
<epilogue>unique optional text blob</epilogue>
</HED>
````
Additional details can be found in [Appendix B](https://docs.google.com/document/d/1icp4fJyCqngSfYy1kPe7FJ-bqA8_Ei67oqn5--0vrDo/edit?usp=sharing) of the specification.

**Comment by VisLab** [comment]
This issue has been addressed by the new version of the schema.
