### ISSUE TITLE
Make explicit restrictions on use of special characters in descriptions and tags

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#16]
Certain characters should not be allowed in tags (particularly this comes up in descriptions and labels). These characters are

parentheses: ( )
comma: ,
tilda: ~

This should be put in the HED schema somewhere

**Comment by dungscout96** [comment]
The use of [XML Schema](https://www.w3schools.com/xml/schema_facets.asp) might be necessary here?

**Comment by VisLab** [comment]
This will be incorporated into issue #33.
