### ISSUE TITLE
Add requireChild to top-level tags

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-specification#17]
Do any of the top-level tags have any intrinsic meaning? What use is tagging something as just an "Event" or an "Item"? All of these top-level tags seem to require using one of their children.

**Comment by VisLab** [comment]
All top level tags should have requireChild as an attribute in the schema.

**Comment by VisLab** [comment]
I have removed the requireChild from top-level tags.  Using the top level tag alone may be particularly useful in conjunction with library schema to indicate what "subtree" the library term is falls into. Also there might be cases where the user does not want to say categorize an event, but wants to indicate that it is an event.
