### ISSUE TITLE
Elimination of tildes

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#171]
Could we consider eliminating the tilde as a valid syntax in HED strings?  Although it is mentioned in the 2016 Bigdely-shamlo et al. paper, it hasn't been used very much and will not be supported in HED 3G at all.  The tilde syntax is:

>  `(a ~ b ~ c)`   where `a` is a noun clause `b` is a verb clause and `c` is a direct object. 

**The proposal**
1.   `(a ~ b ~ c)` will no longer validate.
2.  Users should replace `(a ~ b ~ c)`   with `(a, (b, c))`.  Similarly, `(a ~ b)` should be replaced by `(a, b)`.
3.  If necessary, we can write a tool that takes HED tags and transforms into the new syntax. (We have some other mapping tools for HED 2G into HED 3G and we can incorporate into that tool.) We might also put a specific error message in the validator saying to replace it. 

**Reasons for the proposal**
1. The tilde syntax makes parsing and searching and other things a LOT more complicated for analysis tools downstream, not only for the raw parsing, but also from the ordering requirements on individual components.
2. It is somewhat unnecessary from a semantic view since the tools going forward are assumed to rely on parentheses and types. Along this line, I would for us to eventually develop a more capable `HedString` Python and perhaps Matlab class that could be used for parsing and validation, but would also be used by analysis tool developers. 
3. Very few if any annotated datasets use the tilde notation.  The only one that I am aware of is one that I was planning to re-annotate anyway.

**Cons**
1. It breaks backwards compatibility.

**Comment by VisLab** [comment]
This has been completed in both JavaScript and Python.

**Comment by happy5214** [comment]
To clarify, the JavaScript changes were merged into a development branch that will be merged into master and published to npm at some point this weekend, so OpenNeuro still has the tilde check for now.
