### ISSUE TITLE
mapping HED versions to HED "generations"

### ISSUE THREAD

**Issue by sappelhoff** [hed-standard/hed-specification#172]
Just a comment for a historical perspective after reading the whitepaper the following whitepaper, 

> Robbins, K., Truong, D., Jones, A., Callanan, I., & Makeig, S. (2020, August 1).
Building FAIR functionality: Annotating event-related imaging data using Hierarchical Event Descriptors (HED).
https://doi.org/10.31219/osf.io/5fg73

... I missed some mapping from HED "versions" to the HED "generations". I could find from information of the HED schema release page, that HED version > 8.0.0 will be called HED 3G ("third generation").

However, what was the first version (1.0.0?), and assuming that this was 1G ("first generation"), when did 1G become 2G, and what was the version number at that time?

It'd be interesting to have a table like that:

| version | release date | HED generation |
| --- | --- | --- |
| 1.0.0 | 2012-01-01 | 1G |
| x.x.x | YYYY-MM-DD | 2G |
| 8.0.0 | YYYY-MM-DD | 3G |

with potentially more rows for minor versions and patch versions (assuming that you use [semantic versioning](https://semver.org/), which would also be good to clarify)

**Comment by VisLab** [comment]
Good idea. We'll put a table in soon. We are using semantic versioning now,
but the early versions did not use standard semantic versioning.

**Comment by VisLab** [comment]
I have rewritten the README and added the above table as well as reorganized the hed-specification top level directory.  These changes are currently on the directory-reorg branch.  @sappelhoff when you have a chance could you take a look and see if you have additional suggestions.
Thanks,
Kay

**Comment by sappelhoff** [comment]
> A major redesign of HED, HED-2G released in 2016 (4.0.0 <= HED version <= 8.0.0)

this should probably be: `< 8.0.0`, not `<= 8.0.0`

> The second majoring restructuring, HED-3G (7.x.x < HED version)

couldn't that just be `8.0.0 <= HED version`

>  using a markdown l anguage 

typo there


What is the `hedxml-test/` directory about?

Other than that the reorganization looks like a nice improvement to me. Thanks!

**Comment by VisLab** [comment]
Thanks...  I have made corrections.   Unfortunately 8.0.0 > 8.0.0-alpha.1 etc. so it has to be 7.x.x < HED version.

The `hedxml-test` directory is for putting up proposed changes of the schema to be used for testing and comment. The problem with putting a proposed HED schema in `hedxml` is that then tools start to cache the file and use it for annotation.  I put a `README` in the `hedxml-test` directory to explain this.

**Comment by VisLab** [comment]
This has been addressed in a series of PRs ending with #244.
