### ISSUE TITLE
Distinguish integer-only numeric values

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-specification#19]
There's a semantic distinction between numbers which can only be integers (counters like Attribute/Repetition) and unit-based and other values that can be integers or decimals. Validators could benefit from encoding such counter values in the schema as integer-only.

**Comment by VisLab** [comment]
Add an additional attribute isInteger  (which  replaces isNumeric when the specified value must be an integer).   This requires some addition to the validator and the schema.   This will be useful for RDF parsing in the future.

**Comment by VisLab** [comment]
Issue #400 is broader so I am closing this issue.
