### ISSUE TITLE
Add schema attribute for prefix unit symbols

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-specification#192]
The rewritten unit validation that will be merged into the JavaScript HED validator in https://github.com/hed-standard/hed-javascript/pull/22 will generally involve splitting the value string by the last space and validating the tail as a unit. However, this fails for prefixed units, like the dollar sign (`$`), which have to be special-cased. Rather than checking all units as possible prefix units (which can possibly be an expensive string comparison), can we add a new schema attribute denoting a prefix unit? I only know of the dollar sign among current units, but I feel more comfortable hard-coding an attribute name than a unit symbol, since library schemas may want to introduce similar prefix units (e.g. euros (`€`)).

**Comment by VisLab** [comment]
Does anyone have a suggestion for the name of this attribute? @happy5214 @IanCa

**Comment by happy5214** [comment]
This has been added as `unitPrefix`.
