### ISSUE TITLE
Determine scope of date-time values

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-specification#194]
We will be using ISO 8601 strings for our date-time values, as mandated by BIDS. ISO 8601 includes dates, date-time combinations, and simple times. (This thus subsumes #18.) Partial strings (e.g. HH:mm and YYYY-MM) are allowed by ISO 8601, as are fractional seconds (and even minutes), We need to decide what kinds of ISO 8601 strings will be allowed as HED date-time values.

**Comment by happy5214** [comment]
Also note that the clock face tags do not currently accept values. They should probably allow `dateTime` values once this format is finalized.

**Comment by VisLab** [comment]
clockFace has been eliminated. dateTime has been moved to valueClass.
