### ISSUE TITLE
Add a default attribute to HED XML

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#21]
Unit classes have a default attribute.   We need to be able to add a default to a # for certain cases that over ride the default unit class.

Example:  Direction has unit class angle but its default is degrees not radians.

**Comment by dungscout96** [comment]
Maybe we can add another attribute to HED node called "defaultUnit"? With that if a node has multiple unit classes it must also have the same number of corresponding default units to make it clear for supporting tools?

**Comment by VisLab** [comment]
No, just look at time of unitClass.  No need to specify default for all unitClasses specified.

**Comment by VisLab** [comment]
That was just look at the type of unit that is specified in the default. It is already implemented.  We currently call this default, but we should rename this attribute defaultUnit.

**Comment by VisLab** [comment]
Default units were added with 8.0.0.
