### ISSUE TITLE
Proposal for Consolidating IDs

### ISSUE THREAD

**Issue by Theendeavorer** [hed-standard/hed-specification#22]
# Major HED Restructuring Proposal 1:  

Proposal: Consolidate all IDs under Attribute and eliminate from the rest of the HED Schema.

## Justification:
1. Consolidating the IDs for all the following tags will help to centralize them and allow for them to have a single encompassing tag.

2. This will eliminate most of the passThrough attribute, and will make the remaining ones more conforment with the meaning of passThrough in preperation for RDF mapping.
_____________________________________________________________________________
## Propose the following Attribute:
  
**Attribute** \{requireChild, extensionAllowed\}
  *	ID \{requireChild\}
	  *	Value \{requireChild\}
		  *	\# \{takesValue\}
	  *	Type \{requireChild\}
		  *	Group \{requireChild\}
			  *	\# \{takesValue\}
		  *	State \{requireChild\}
			  *	\# \{takesValue\}
		  *	State ID \{requireChild\}
			  *	\# \{takesValue\}
		  *	Local \{requireChild\}
			  *	\# \{takesValue\}
		  *	Reference \{requireChild\}
			  *	\# \{takesValue\}
		  *	Participant \{requireChild\}
			  *	\# \{takesValue\}
		  *	Permutation \{requireChild\}
			  *	\# \{takesValue\}
__________________________________________________________________________
## Tags to Replace:
**Event**  
  *	Category \{required, requireChild, predicateType=passThrough, position=1\}  
	  *	ID \{predicateType=propertyOf\}  
		  *	\#  \{takesValue\}

**Event**
  * Category \{required, requireChild, predicateType=passThrough, position=1\}  
	  *	Experimental control
		  *	Sequence\{predicateType=propertyOf\}
			  *	Permutation ID\{requireChild\}
				  *	\# \{takesValue\}

**Event**
  *	Category \{required, requireChild, predicateType=passThrough, position=1\}
	  *	Group ID \{predicateType=propertyOf\}
		  *	\# \{takesValue\}

**Item**
  *	ID \{requireChild, predicateType=propertyOf\}
	  *	\# \{takesValue\}

**Item**
  *	ID \{requireChild, predicateType=propertyOf\}
	  *	Local
		  *	\# \{takesValue\}

**Item**
  *	Group ID \{requireChild, predicateType=propertyOf\}
	  *	\# \{takesValue\}

**Sensory presentation** \{extensionAllowed\}
  *	Visual 
	  *	Rendering Type  \{requireChild, predicateType=passThrough\}
		  *	Screen
			  *	View Port
				  *	ID \{predicateType=passThrough\}
					  *	\# \{takesValue\} 

**Attribute** \{requireChild, extensionAllowed\}
  *	State ID \{requireChild\}
	  *	\# \{takesValue\}

**Attribute** \{requireChild, extensionAllowed\}
  *	Object side \{requireChild\}
	  *	Reference object ID \{requireChild,predicateType=propertyOf\}
		  *	\# \{takesValue\}

**Attribute** \{requireChild, extensionAllowed\}
  *	Reference frame \{requireChild\}
	  *	Relative to participant 
		  *	Participant ID \{requireChild\}
			  *	\# \{takesValue\}

**Participant** \{predicateType=passThrough\}
  *	ID \{requireChild, predicateType=propertyOf\} 
	  *	\# \{takesValue\}

**Comment by dungscout96** [comment]
Please add comments to clarify what values of the ID type tags can or are meant to take - Scott & Dung

**Comment by VisLab** [comment]
Now that I look at this again, I agree that under the various Attribute/ID/Type/xxx  we should remove the requireChild attribute and the takes value for this proposal.

**Comment by VisLab** [comment]
## Proposal for consolidating IDs, version 2
  
**Attribute** \{requireChild, extensionAllowed\}
  *	ID \{requireChild\}
	  *	Value \{requireChild\}
		  *	\# \{takesValue\}
	  *	Type \{requireChild\}
		  *	Group 
		  *	State
		  *	State ID 
		  *	Local 
		  *	Reference 
		  *	Participant 
		  *	Permutation 

The propertyOf attribute in the XML schema is no longer necessary if all properties are under attribute.

Also some IDs in the current schema (such as participant ID) had an attribute of numeric, which it shouldn't have had.  Any string should be allowed as an ID.

**Comment by dungscout96** [comment]
We think the syntax can be shorten by introducing a new type "Index". Any ID that doesn't belong to a specific group will be of "Index" type. Then we remove "Value" and "Type" subtree and allow specifying ID value directly without grouping.

* ID
    * Index
        * \#
    * Group
        * \#
    * State
        * \#
    * State ID
        * \#
    * Local
        * \#
    * Reference
        * \#
    * Participant
        * \#
    * Permutation
        * \#
- Scott & Dung

**Comment by VisLab** [comment]
I agree --- am making this change in the next pull request.
