### ISSUE TITLE
XML format change to include property

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#225]
I am thinking we should have the schema properties part of the schema. Currently they are listed in the epilogue section of the XML file:

````xml

    !# end hed

    This is the new format for the mediawiki schema. The schema attributes are designed to be checked in software rather than hard-coded. The schema attributes, themselves have properties. These are:

    * boolProperty - indicates that that attribute represents something that is either true or false and does not have a value. Attributes without this value are assumed to have string values.
    * unitClassProperty - indicates that this attribute is designed to be applied to unit classes.
    * unitModifierProperty - indicates that this attribute is designed to be applied to unit classes.
    * unitProperty - indicates that this a applies to units within a unit class. 
````

I think that it would be better to put them in the schema as:

````xml

<propertyDefinitions>
    <propertyDefinition>
        <name>boolProperty</name>
        <description>Indicates that that attribute represents something that is either true or false and does not have a value. Attributes without this value are assumed to have string values.</description>
    </propertyDefinition>
</propertyDefinitions>

````
The reason that I am thinking of this is that then everything is in the XML and can be specified using an XSD.   I think it will mainly affect the python schema stuff, but probably the JavaScript and Matlab readers will have to be adjusted.

If there are no objections, I would like to go ahead with this before we release HED-3G, but I would like to hear comments from @IanCa  @happy5214 @dungscout96 about potential implications.

**Comment by IanCa** [comment]
They'll still need to be hardcoded to do anything, and the readers will need to go properties -> attributes -> tags/units/modifiers.

I don't think these are major problems, just the main implications I know of.

**Comment by happy5214** [comment]
@VisLab and I discussed this a couple of weeks ago. I was against including these as schema elements because I feel the properties are aspects of the specification, not of the individual schemas. Unless we're creating new schema-specific properties, I feel there's nothing to be gained by including them in the schemas in a structured form.

**Comment by VisLab** [comment]
I have been working on an XSD to be used to specify the structure of and to validate XML HED schema.  This specification is needed to nail down the structure of the schema, particularly as we move forward with library schema.  I was hoping to include an XSD as part of the initial release of HED8.0.0.

The `hedxsd-test` directory of the hed-specification repository has a draft of the XSD and the proposed structure for the XML. At the end of the XSD is the specification of the `HED` structure in terms of the previously-defined complex types.  

I am thinking that we should actually require all of the sections (even when they are empty). I have included the `property` specification as part of this as well. The reason that I now think it should be in is that the schema validators should eventually check that there aren't any random properties associated with the schema attribute section.   Most of this is relevant only to schema validation and not to HED validators.  Hence, if the JavaScript and Python HED validators won't have any issue with ignoring it, there shouldn't be a problem.

Could @IanCa and @happy5214 and @dungscout96 verify that the `property` section can be easily ignored when reading the HED schema for processing?  I would appreciate it if you could also look over the proposed XSD and see if you spot any issues.  I have validated using several online validators, but they all require me to explicitly load the XSD. 

@sappelhoff: any comments you have on this would be appreciated too.

**Comment by VisLab** [comment]
Also, does anyone see any problems if we end up putting the XSD file in the `hedxml` directory?

**Comment by VisLab** [comment]
These changes have been incorporated into HED8.0.0-beta.3
