### ISSUE TITLE
Proposal for Removing Plurals from Unit classes

### ISSUE THREAD

**Issue by Theendeavorer** [hed-standard/hed-specification#23]
# Unit Improvement Proposal 1:
## Justification:
1. Elminate explicit mention of plural units in the HED Schema and replace with
 validator, and have validator automatically try plurals.
2. Add a noPlural attribute to explicitly mark items with no plural or whose
 singular and plural are the same.
_______________________________________________________________________
## Change these:
**Unit classes**
  * acceleration
	  * m-per-s2\{noPlural\}
	  * cm-per-s2 \{noPlural\}
  * currency 
	  * dollars(Change to dollar)\{noPlural\}
	  * $\{noPlural\}
	  * points(Change to point)\{noPlural\}
	  * fraction\{noPlural\}
  * frequency
	  * Hz\{noPlural\}
	  * mHz \{noPlural\}
	  * Hertz\{noPlural\}
	  * kHz \{noPlural\}
  * intensity
	  * dB \{noPlural\}
  * jerk
	  * m-per-s3 \{noPlural\}
	  * cm-per-s3 \{noPlural\}
  * luminousIntensity
	  * candela \{noPlural\}
	  * cd \{noPlural\}
  * memorySize
	  * mb \{noPlural\}
	  * kb \{noPlural\}
	  * gb \{noPlural\}
	  * tb \{noPlural\}
  * physicalLength
	  * m \{noPlural\}
	  * cm \{noPlural\}
	  * km \{noPlural\}
	  * mm \{noPlural\}
	  * foot \{noPlural\}
	  * feet \{noPlural\}
  * pixels
	  * px \{noPlural\}
  * speed
	  * m-per-s \{noPlural\}
	  * mph \{noPlural\}
	  * kph \{noPlural\}
	  * cm-per-s \{noPlural\}
  * time
	  * s \{noPlural\}
	  * hour:min \{noPlural\}
	  * cs \{noPlural\}
	  * ms \{noPlural\}
  * area
	  * m2 \{noPlural\}
	  * cm2 \{noPlural\}
	  * km2 \{noPlural\}
	  * px2 \{noPlural\}
	  * pixel2 \{noPlural\}
	  * mm2 \{noPlural\}
  * volume
	  * m3 \{noPlural\}
	  * cm3 \{noPlural\}
	  * mm3 \{noPlural\}
	  * km3 \{noPlural\}
________________________________________________________________________	
## Remove these:
**Unit classes**
  * angle \{default=radians\}
	  * degrees(remove)
	  * radians(remove)
	  * physicalLength \{default=cm\}
	  * meters(remove)
	  * miles(remove)
  * pixels \{default=px\}
	  * pixels(remove)
  * time \{default=s\}
	  * seconds(remove)
	  * centiseconds(remove)
	  * days(remove)
	  * milliseconds(remove)
	  * minutes(remove)
	  * hours(remove)
  * area 
	  * pixels2(remove)

**Comment by VisLab** [comment]
Another justification for this is that we are inconsistent about which plurals are in the schema.  We can handle this is in the validator.

**Comment by dungscout96** [comment]
I agree. The extraction tool will need to be updated to automatically try out plurals as well. Should we share a list of accepted plurals for consistency among tools?

**Comment by VisLab** [comment]
Both python and javascript have standard pluralize functions that allow getting the plural or singular in English. We would need to add an attribute indicating that a given unit had only one form for singular and plural.   We would need to update the validator to handle this.  We would need to discuss extraction ---- most of the extraction tools first put the HED string into a standardized form.  This would need to be addressed there.

**Comment by VisLab** [comment]
**Change these unit classes** (corrected)

    acceleration
        m-per-s2{noPlural}
        cm-per-s2 {noPlural}
    currency
        dollars(Change to dollar)~~{noPlural}~~
        ${noPlural}
        points(Change to point)~~{noPlural}~~
        fraction ~~{noPlural}~~
    frequency
        Hz{noPlural}
        mHz {noPlural}
        Hertz{noPlural}
        kHz {noPlural}
    intensity
        dB {noPlural}
    jerk
        m-per-s3 {noPlural}
        cm-per-s3 {noPlural}
    luminousIntensity
        candela ~~{noPlural}~~
        cd {noPlural}
    memorySize
        mb {noPlural}
        kb {noPlural}
        gb {noPlural}
        tb {noPlural}
    physicalLength
        m {noPlural}
        cm {noPlural}
        km {noPlural}
        mm {noPlural}
        foot ~~{noPlural}~~
        ~~feet {noPlural}~~
    pixels
        px {noPlural}
    speed
        m-per-s {noPlural}
        mph {noPlural}
        kph {noPlural}
        cm-per-s {noPlural}
    time
        s {noPlural}
        hour:min {noPlural}
        cs {noPlural}
        ms {noPlural}
    area
        m2 {noPlural}
        cm2 {noPlural}
        km2 {noPlural}
        px2 {noPlural}
        pixel2 {noPlural}
        mm2 {noPlural}
    volume
        m3 {noPlural}
        cm3 {noPlural}
        mm3 {noPlural}
        km3 {noPlural}

**Comment by VisLab** [comment]
This unit modifiers and elimination of plurals have been incorporated into all branches of the specification and the javascript and python validators.
