### ISSUE TITLE
Add stimulus event participant imperative tags and deprecation of Target and Oddball tags

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-specification#24]
For brain imaging studies, the imperative significance of stimulus events within the experimental paradigm has crucial effect on participant brain dynamics. 

Proposal: add a subclass 'Imperative effect' under Attribute that would take an Action child. This tag should be grouped with tags describing stimulus event.

**Attribute** \{requireChild, extensionAllowed\}
  *	Imperative effect \{requireChild\}
	  *	Action \{requireChild, extensionAllowed\}

For example, presentation of a certain sensory stimulus might require the participant to press a button (Attribute/Imperative effect/Action/Button press), add to an internal count (Attribute/Imperative effect/Mental count/Increment), etc. 

**Note:** the jargon term often used in ERP laboratories, 'Target', typically denotes a stimulus event that functions as an imperative command to the participant to press a button, etc. 

We should deprecate the tags Participant effect/Cognitive/Target and also Participant effect/Cognitive/Oddball. For Target, taggers should use Attribute/Imperative effect. For Oddball, they should use 'Attribute/Relative probability' for mean percentage of stimulus presentation events in this stimulus class (which should take only numerical percentage value) and 'Attribute/Occurrence rate' for the mean number per minute of events in this class (unit can be event-per-minute).

-- Scott & Dung

**Comment by VisLab** [comment]
Attribute/Imperative effect seems like a good idea.  However, I am concerned about putting an Action tag under this.  This breaks the orthogonality.  In theory we would have to duplicate the entire Action hierarchy under this attribute.  We could just use parentheses and indicate that this tag is expected to be grouped with an Action.

I am still not sure I understand why this shouldn't be under Participant effect.   We will need to then review all of the tags under this.

**Comment by VisLab** [comment]
This has been addressed by the Task-property/Task-effect-evidence.  The terminology is now clearer and the tagging strategy is also clearer.

**Comment by VisLab** [comment]
This has been addressed.
