### ISSUE TITLE
Proposal for Shapes Regrouping

### ISSUE THREAD

**Issue by Theendeavorer** [hed-standard/hed-specification#25]
# Shapes Regrouping Proposal 1:
## Justification:
1. Some shapes were missing from the list, so they are added here for 
completeness.
2. Add in attribute for the number of sides for a prism, pyramid or polygon.
________________________________________________________________________
## Move specific 3D Shapes under 3D Shape:
**Item**
   * 3D shape
		* Sphere
		* Box
			* Cube
________________________________________________________________________
## Add in these:
**Item**
   * 3D shape
		* Prism 
		* Pyramid 	
		* Cone
		* Cylinder
		* Torus
		* Oviod
		* Ellipsoid
   * 2D shape
		* Polygon 

**Attribute**
   * Number of sides {requireChild}
	   * \# \{takesValue\}

**Comment by VisLab** [comment]
To better organize hierarchy under Item:

1)  Create a new tag:   Item/Geometric shape
2)  Move  2D shape subtree,  Pattern subtree, and 3D shape subtree under Item/Geometric shape

**Comment by bigdelys** [comment]
I am not sure what is under the 'Pattern' subtree can be considered  'geometric shape':

Pattern
-Checkerboard
-Abstract
-Fractal
-LED
-Dots
-Random dot
-Complex

We could move the '2D shape' and '3D shape' under a new tag (Item/Geometric shape) and convert 2D shape -> 2D, 3D Shape -> 3D. What do you think?

**Comment by happy5214** [comment]
I concur. Patterns are often *made of* shapes, but they are not themselves shapes. 3D shapes aren't really objects (Item/Object otherwise includes only real-world, non-abstract objects), so the shared Item/Geometric shape parent makes sense.

**Comment by touryan** [comment]
I suggest adding Hitbox at the shape level (or under 3D shape) to distinguish between a simulated object's appearance (e.g. sphere) and its collision/interaction geometry (e.g. cube).

**Comment by VisLab** [comment]
This is a good idea.   Should Hitbox be an attribute or the item itself?  Suppose we had a sphere....

(Item/3D shape/Sphere, Attribute/....

Here I am stuck.  We don't have a good way of specifying the center of the object in a uniform way. We don't have a way of specifying the radius.  We do have an attribute for volume so we could do volume.  I think we need to address this.

**Comment by dungscout96** [comment]
I resonate with the need to have a way of specifying the radius. Maybe add Attribute/Size/Radius?
I have been using Attribute/Location/Screen to specify locations of the object's center. Is it related to your comment? I would love to know to make sure I've used that tag correctly.

**Comment by VisLab** [comment]
This is a more general problem...... the objects may not be on the screen
but may be in the real world.  I think we need some type of frame of
reference specification.
