### ISSUE TITLE
Schema reorganizations before release (Beta-5)

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#269]
We have been debating various changes to the HED schema by email, but I think they are better served if we document our discussions here.

I have been going over the HED schema and looking at how HED terms correspond to OBO ontologies.  Binary relations are well-separated from properties on OBO ontologies.  (Currently HED relations are under Attributes/Relational.)  Here is a possible reorganization that distinguishes Property from Relation:

I have been looking at the schema with an eye towards ontologies. 

Here is a potential reorganization of the schema.

- **Event**
- **Action**
- **Agent**
- **Item**
- **Property**
  - Agent-property
  - Data-property
  - Environmental-property
  - Informational-property
    - Categorical
    - Metadata
      - Def
      - Def-expand
      - Definition....
    - Organizational     
  - Sensory-property
    - Sensory-modality
    - Sensory-quality
      - Optical-quality
  - Task-property
- **Relation**
  - Comparative-relation
  - Connective-relation
  - Ordering-relation
  - Spatiotemporal-relation

The idea is that **Relation** (should represent binary relation as it does in the ontology) and be separate from **Property** which is just about that thing.

Comments @smakeig @dungscout96

**Comment by VisLab** [comment]
I have changed Attribute to Property and grouped some of the other property categories under that.

**Comment by smakeig** [comment]
Yes, sounds logical ... and shouldn't interfere with short-from annotating ...

**Comment by VisLab** [comment]
I am moving the Def, Def-expand and Definition under Organizational rather than Informational.  There are other items under the original Informational which should be metadata.  This will take a couple of iterations.

**Comment by VisLab** [comment]
The **Categorical**  subtree which is currently under Informational should be moved under **Data-property/Data-type**.  This subtree is a specification of commonly used enumerated types.

**Comment by VisLab** [comment]
I am eliminating Thermal-relational.  That had 4 entries:

Hot and Cold I am moving to Categorical-level

The Hotter-than and Colder-than  can be covered by Greater-than and Less-than.  If A has a temperature greater than B's. We can tag:

(Temperature, (A, (Greater-than, B)))

This strategy allows any property of A to be compared to B.  The tools just need to know about it.

**Comment by VisLab** [comment]
I am changing the following:
**Directional-relation/Opening**   to   **Move/Perform/Open**
**Directional-relation/Closing**   to   **Move/Perform/Close**

**Reasons:**
1. Opening is not strictly a binary relationship
2. The OBO ontologies seem to use Opening to mean an Opening in something (like an incision).

**Comment by VisLab** [comment]
**Proposed change:**   Under **Metadata** add **OBO-identifier**.  
**Reason:** This would allow a user to use any OBO ontology term in a HED annotation as a reference.

**Comment by VisLab** [comment]
The items in this were agreed upon in a meeting of 7/27/2021 with @smakeig @dungscout96 @VisLab.  This issue is being closed and individual additional sub-items will be considered as individual issues that reference this issue number.
