### ISSUE TITLE
Versioning convention for HED restructuring

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#28]
The HED restructuring will require both changes in data that has been previously tagged and changes in the validator code itself.

The semantic versioning:  
MAJOR  (api changes)
MINOR   (add functionality backwards compatible)
PATCH  (fix bugs)

doesn't really help us in getting stuff done.  Since this restructuring will be internal and will lead to just one major version change in HED itself, I propose the following convention:

MAJOR  (requires validator code to be modified)
MINOR  (requires data tagged under previous version to be retagged, but validator does not change)
PATCH  (does not require data tagged under previous version to be retagged nor does it require validator code to be modified)

Please let me know if this is okay going forward.

**Comment by dungscout96** [comment]
Changes to validator most likely mean changes to CTAGGER as well. Better to mention it explicitly "... validator and tagger code..."?

**Comment by VisLab** [comment]
Yes, we should.  My plan is to produce an xml file for each version so that
we can do testing.

**Comment by bigdelys** [comment]
Good idea.
