### ISSUE TITLE
Reorganization of Data-property subtree

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#281]
A discussion of the **Data-property** subtree on 7/27/2021 (@smakeig @dungscout96 @VisLab) centered around whether **Data-property** things should only pertain to the data itself or also the things that happen in events.  The separation is not completely clear as yet.  

It was agreed to move **Physical-property** and **Spatiotemporal-property** out of **Data-property** since they most certainly can apply to both the experimental data, to the events and to the participants.

Reference issue #269

**Comment by VisLab** [comment]
I took Spatiotemporal-property out of Data-property, but I think it belongs back in there.

**Comment by VisLab** [comment]
Moved **Spatio-temporal-property/Resolution** to **Data-property/Resolution**.   We should review whether we just need one Resolution, maybe **Sensor-resolution** which would be grouped with whatever it was the resolution of.   Maybe this should be a **Quantitative-property**?

**Comment by VisLab** [comment]
After a lengthy discussion (@smakeig @dungscout96 and @VisLab)

**Repetition-number** is now **Occurrence-number** and **Repetition-interval** is now **Recurrence-interval**.  The descriptions now rephrase in terms of **Event-stream** with examples. 

The goal is to be able to define named sequences of events and tag their relative positions within a stream.

**Comment by VisLab** [comment]
Added placeholder # to **Organization-property** children such as **Event-stream** and **Condition-variable** to eliminate the need for extra labels.

Now instead of tagging **(Condition-variable, Label/CondHot)**, we tag **Condition-variable/CondHot**.

**Comment by VisLab** [comment]
I'm moving the  **Data-property/Quantitative-property** subtree to **Data-property/Data-value/Quantitative-value**.

The use of **Quantitative-property** is confusing.

Similarly, I am moving **Data-property/Statistical-property** subtree to **Data-property/Data-value/Statistical-value**

These moves put various potential values on the same footing.

**Comment by VisLab** [comment]
**Question** (@smakeig @dungscout96):  Under  **Property/Data-property/Data-value/Spatiotemporal-value/Temporal-value**:

**Onset**, **Offset**, **Pause**, **Time-sync**, and **Time-out** are all used to mark or label something in the data.  In contrast, **Delay**, **Duration**, **Time-value**, and **Time-interval** are used to specify to values.  

Should they be divided out?    Maybe the first group should be in a **Data-marker/Time-marker** subtree rather than the **Data-value** subtree.

**Comment by VisLab** [comment]
Suggest the following organization to clearly delineate between markers in the data and things that are values.

Property
- Data-property
  - Data-marker
    - Spatial-marker
    - Temporal-marker
      - Offset
      - Onset
      - Pause
      - Time-out
      - Time-sync
  - Data-resolution
  - Data-source-type
  - Data-value

**Comment by smakeig** [comment]
How would 'Spatial-marker' be used? ...

On Mon, Aug 2, 2021 at 10:47 AM VisLab ***@***.***> wrote:

> Suggest the following organization to clearly delineate between markers in
> the data and things that are values.
>
> Property
>
>    - Data-property
>       - Data-marker
>          - Spatial-marker
>          - Temporal-marker
>             - Offset
>             - Onset
>             - Pause
>             - Time-out
>             - Time-sync
>          - Data-resolution
>       - Data-source-type
>       - Data-value
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hed-2Dstandard_hed-2Dspecification_issues_281-23issuecomment-2D891087233&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=KEnFjcsfiKF_BPOsgvPP9w&m=LPgPYgdyY9MP1AB9Z_metPnIDXr5u0tfDbxr6qmI4cc&s=FxdvMbA-GEQGqGxOyH-wY4ZtNTNhQY9InobsyY49h5g&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKN2SFSBCV5MBUIKB76GAFTT22VXBANCNFSM5BDEXWZQ&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=KEnFjcsfiKF_BPOsgvPP9w&m=LPgPYgdyY9MP1AB9Z_metPnIDXr5u0tfDbxr6qmI4cc&s=UGNhCbazYq2sgTF039x4NM3qu46BvkHvEvrNioxBbsc&e=>
> .
>


-- 
Scott Makeig, Research Scientist and Director, Swartz Center for
Computational Neuroscience, Institute for Neural Computation, University of
California San Diego, La Jolla CA 92093-0559, http://sccn.ucsd.edu/~scott

**Comment by VisLab** [comment]
This was discussed 8/2/2021 (@smakeig @dungscout96 @VisLab) and agreed upon.
