### ISSUE TITLE
Remove the Paradigm subtree from HED and create an independent hierarchy for task annotation (HTD)

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#29]
We had a lengthy discussion about what to do with the Paradigm subtree and didn't come to any conclusions.  I propose that it be removed entirely.  We haven't really used it to tag.  It really doesn't apply directly to individual events.  This is the Hierarchical Event Descriptors.  Relationships of particular events to paradigms could be given in the Event/Description.

In the future, we could work on a HTD  (Hierarchical Task Descriptors), which would just be a separate schema for describing tasks.  

Removing Paradigm subtree would greatly shorten the hierarchy and make it easier for users to focus on tagging events.

**Comment by VisLab** [comment]
The validators should be able to work without little change as they work based on a schema, which is settable.

**Comment by bigdelys** [comment]
I think we should have a fully fleshed-out alternative before removing the Paradigm subtree. Knowing the paradigm is very important in making sense of individual events.

**Comment by VisLab** [comment]
Paradigm is not in 3G.  Instead it is expected that Paradigm will be linked to other ontologies such as CogPo using the Metadata tag.
