### ISSUE TITLE
We need to clean up the extensionsAllowed attribute in the HED schema

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#3]
Three things need to be fixed:
1)   The top level **Custom** tag should have the extensionsAllowed attribute.

2)   All tags under the top level **Attribute** tag should have their extensionsAllowed Attributes removed as they inherit from Attribute.

3)   All tags under the top level **Item** tag should have their extensionsAllowed Attributes removed as they inherit from Item.

**Comment by bigdelys** [comment]
1- Done.

2- Done.

3- I think you mean under **Item/Object** since **Item** does not have **extensionAllowed**, only **Object** does. Done.
