### ISSUE TITLE
Reorganization of Informational-property

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#303]
**Informational-property/Experimental-note** moved to **Informational-property/Metadata/Experimental-note**.  

**Reason:**   Entities not meant to be part of tag string should be under **Metadata**.  **Description** and **Label** are meant to be part of the tag string.

Removing **Parameter** and **Value**.   **Value** clearly doesn't belong and we don't have a system for specifying parameters in a machine actionable way so it is better to wait until we do.

I am moving **Organizational-property** be moved under **Informational-property**. This reduces the number of distinct categories under **Property** to 7 which is more manageable.   Also, it wasn't clear what the difference was. This makes **Organization-property** a subcategory of I**nformational-property**.

**Comment by VisLab** [comment]
On the last paragraph.  **Organizational-property** is now back at the same level as **Informational-property**.

**Comment by dungscout96** [comment]
Can you clarify what you meant by "not meant to be part of tag string"?

I agree with the rethinking that Organization-property doesn't belong under Informational-property

**Comment by VisLab** [comment]
This was discussed 8/2/2021 @smakeig @dungscout96 @VisLab and agreed upon.
