### ISSUE TITLE
Data-property/Physical-property needs reorganization

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#304]
We will need to have a discussion about how to reorganize this subtree.   There should be a clear distinction about things that are actual properties of a material (like conductivity) and things that are thermodynamic in nature, like energy and temperature and not intrinsic to the material.   @dungscout96 @smakeig.

**Comment by smakeig** [comment]
temperature --> air-temperature


On Sat, Jul 31, 2021 at 11:24 AM VisLab ***@***.***> wrote:

> We will need to have a discussion about how to reorganize this subtree.
> There should be a clear distinction about things that are actual properties
> of a material (like conductivity) and things that are thermodynamic in
> nature, like energy and temperature and not intrinsic to the material.
> @dungscout96
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dungscout96&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=KEnFjcsfiKF_BPOsgvPP9w&m=8ceC2Wa1_YTeBjCMgG4mSv3rPIwfF1zcAVwUyLsoWqs&s=e7gGYJivXesLD_oTofXFriDpxGnBbGRG9PVNa6ezMqw&e=>
> @smakeig
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smakeig&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=KEnFjcsfiKF_BPOsgvPP9w&m=8ceC2Wa1_YTeBjCMgG4mSv3rPIwfF1zcAVwUyLsoWqs&s=n--wnDqq_MzVL2VNn09esnhYXKeU73cZ2a8rsXNWEYw&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hed-2Dstandard_hed-2Dspecification_issues_304&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=KEnFjcsfiKF_BPOsgvPP9w&m=8ceC2Wa1_YTeBjCMgG4mSv3rPIwfF1zcAVwUyLsoWqs&s=AqRlNMaz0bMzTthz8wnZYnBmnVzZT7vztDODPNPvud0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKN2SFSAZPJ7Y5HKC6UQ45DT2QIRHANCNFSM5BKDYLAQ&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=KEnFjcsfiKF_BPOsgvPP9w&m=8ceC2Wa1_YTeBjCMgG4mSv3rPIwfF1zcAVwUyLsoWqs&s=fEYgZyukPlcaTjlt0YWZNbb3x6lTaGlfaCgs8qpmJEU&e=>
> .
>


-- 
Scott Makeig, Research Scientist and Director, Swartz Center for
Computational Neuroscience, Institute for Neural Computation, University of
California San Diego, La Jolla CA 92093-0559, http://sccn.ucsd.edu/~scott

**Comment by VisLab** [comment]
**Air-temperature** should probably be in **Environmental-property** not **Physical-property**.  

Is there a reason to keep the **Physical-property** subtree at all?

**Comment by VisLab** [comment]
It was agreed to completely remove the Physical-property subtree at meeting 8/2/2021 @smakeig, @dungscout96 @VisLab.
