### ISSUE TITLE
Create strict guidelines for characters to be used in new tags as well as labels and descriptions

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#33]
We need to create a detailed specification of which characters can be used in tags and descriptions. We also need to create guidelines for tags, labels, and descriptions to improve validators ability to validate and more importantly to make tags with values more usable in analysis.

**Comment by VisLab** [comment]
The HED-3G specification now contains:

 _"In HED strings, # term placeholders represent user-supplied values. In addition to alphanumeric characters, they may contain +, -, and ^ (addition, subtraction, exponentiation), : (clock times), $ (currency) and periods (decimal points). These values may not contain other punctuation. A limited number of special Unicode characters may be allowed if explicitly specified in the HED schema."

The value parameters in HED spreadsheets can follow these rules.  Can you write some test cases for this.  There should also be a well-defined place in the validator where this is checked so that if it needs to be changed in the future it will be easier to find._  

We need a method of specifying this in the specification so that validator can check.

**Comment by VisLab** [comment]
Related to issue #16

**Comment by VisLab** [comment]
Also related to issue #73

**Comment by happy5214** [comment]
Is this done? If not, what still needs to be worked on?

**Comment by VisLab** [comment]
After some discussion we have added a `nameClass` and `textClass` to the unit classes.  Like `posixPath` these unit classes have no units associated with them. The idea is to use the `allowedCharacter` attribute of these unit classes to specify which characters are allowed for things like paths, labels, and descriptions.

Initially, we also had a `numericClass` for the same purpose but I backed that out because we may need a more extensive typing system later.

We need to decide whether we are going to in some way allow regex to specify which characters in the schema or whether we will list an attribute for each character or whether we will have a string of allowed characters.  (One of the problems is how to specify that a blank is allowed for individual characters.)  Also reference issue #19.

I would appreciate comments. @happy5214 @dungscout96 @IanCa @sappelhoff

**Comment by IanCa** [comment]
I think number parsing and validation itself should be mostly hardcoded and considered an implementation detail, regardless of how it's done internally.(re, casting, etc)

I think we should add something like "numericUnit" to unit classes.

eg wiki formatted:
*acceleration {defaultUnits=m-per-s^2, numericUnit}
**m-per-s^2 {SIUnit, unitSymbol} 
*numericClass {numericUnit} 

If it has the numericUnit property, it expects a number, in addition to any possible units given.  numericClass would have no units, so it would only expect and validate a number with no units.  This would entirely replace the current isNumeric tag node attribute.

We could still add attributes like min/max or integer only on a unit class, unit class unit, or tag basis, depending on what implementation was desired.

**Comment by happy5214** [comment]
I think values are sufficiently distinct from units that they should have a separate value class element hierarchy. Regexes would be the best way to provide the necessary detail for issues like integer-only values, whether we put them in the schema or hardcode them into the validators. It could also serve as a second layer for the ISO 8601 datetime validation.

**Comment by VisLab** [comment]
In thinking about this --- it would allow some future flexibility.  I am worried about the current design as being too inflexible.

**Proposal:**  
- Add `valueClass` in parallel to `unitClass` 
- Move `posixPath`, `textClass`, `nameClass`, `numericClass` under `valueClass`

We would not make any significant changes to how the validators handle anything except being able to read the new schema for the first release.  In other words, we would not for the first release change the underlying validation.  The release notes would state that the current release 8.0.0 would not verify details of the what characters are allowed in the specification.  This would allow us to add the validation incrementally.  I am seriously thinking about making this change today as beta.3 and have a corresponding xsd beta.3.  Because we are targeting a July 15 release date, we need to decide very soon.

@IanCa @happy5214 @dungscout96 @sappelhoff comments would be very much appreciated.

**Comment by VisLab** [comment]
Value classes now fill this role. They will continued to be developed going forward.

**Comment by VisLab** [comment]
Done with release 8.0.0.
