### ISSUE TITLE
Global restructuring: Attribute subtree is very flat and needs to be restructured

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#39]
There are an enormous number of top-level tags under Attribute and they are very disorganized.  The Attribute/Visual and Attribute/Auditory have reasonable subtrees under them. In the following, I propose to add two categories to group some of the terms: Atttribute/Temporal and Attribute/Spatial which gathers some of the items:

**Temporal** 
  - Onset  
  - Offset
  - Duration 
  - Repetition
  - Temporal rate 
  - Temporal uncertainty 
  - Response start delay 
  - Response end delay 

**Spatial**
  - Object side 
  - Direction 
  - Location 
  - Object orientation 
  - Size 
  - Path 

**That leaves the following enormous list of top level items under Attribute:**
* Peak  
* Nonlinguistic 
* Semantic 
* Language 
* Induced 
* Emotional 
* Priming 
* Subliminal 
* Supraliminal 
* Liminal
* Probability  
* Presentation 
* Item count 
* Intended effect 
* Instruction
* Participant indication 
* File 
* Object control 
* Association 
* Extraneous 
* Role 
* Imagined 
* Condition 
* Action judgment 
* Social 
* Blink

**Comment by dungscout96** [comment]
I agree. A related idea is to create a (RDF?) mapping between Attribute tags and the main tag they modify. This can be used by the schema visualizer and CTAGGER to make it explicitly and immediately clear to users 1) what tags the Attribute can modify and 2) what attributes users can (and should) specify for the tag.

**Comment by VisLab** [comment]
Alexander has essentially done an RDF mapping.   He has gotten quite far along on this.  It is not ready for release and can be made more robust once the schema has been reorganized.  (Dung, I've shared the repository with you so that you can see what Alexander has done so far.)

**Comment by VisLab** [comment]
I would suggest that the following be grouped in some way in a subcategory (what?) under Attribute: Nonlinguistic, Semantic, Language

Maybe this category could be Attribute/Communication  or Attribute/Meaning   suggestions?

**Comment by VisLab** [comment]
Maybe the following could be grouped under the subcategory Attribute/Relationship

Role, Association, Social

**Comment by happy5214** [comment]
Subliminal, superliminal, and liminal can all be grouped under Attribute/Liminality.

**Comment by dungscout96** [comment]
I'm not sure about the use of Attribute/Participant indication. The description says: "This tag is placed in events of type Event/Category/Participant response and grouped with Participant/Effect/Cognitive/.. tags to specify the type of cognitive effect the participant has experienced...." 
But Isn't that using a Participant/Effect/Cognitive tag without Attribute/Intended effect already means that the participant experienced the effect?

**Comment by dungscout96** [comment]
Can we create a group Attribute/Cognitive effect?

* Cognitive effect
   * Induced
   * Emotional
   * Priming
   * Liminality
   * Subliminal
   * Supraliminal
   * Liminal
   * Intended effect
   * Imagined

**Comment by dungscout96** [comment]
Should Action judgment be a subtree of Event/Category/Experiment control? And Event/Category/Experimental control/Action judgement/Incorrect can replace Event/Category/Participant failure?

**Comment by dungscout96** [comment]
Maybe we can create Attribute/Name. If we move File under Item somewhere then we can replace these tags:
Action/Name ==> (Action, Attribute/Name)
Attribute/File/Name ==> (Item/*/File, Attribute/Name)
Attribute/File/Size ==> (Item/*/File, Attribute/Size)
Attribute/File/# ==> (Item/*/File, Attribute/Item count/#)

**Comment by VisLab** [comment]
The Attribute tree has been significantly restructure and Task-property, Agent-property, and Data-property have been split out into separate subtrees.  The remaining attribute nodes are very general terms that could be applied anywhere.  Some additional restructuring may occur later, but this has basically been addressed.
