### ISSUE TITLE
How to represent cause and effects?

### ISSUE THREAD

**Issue by jiversen** [hed-standard/hed-specification#4]
Hi, using HED for the first time seriously. A couple of questions about how to best encode some ideas. I didn't see anything in the existing tags, or maybe I missed it. Of course I can add whatever, but would like your feedback on the best way to do so.

I have stimulus events and want to include information about the cause of the event (e.g. a subject-specific action type). Something like /Attribute/Cause/xxxx

I have stimulus events that have variable meaning to the participant, and are expected or unexpected. /Attribute/Reaction/xxx or /Attribute/Meaning/xxx

**Comment by bigdelys** [comment]
I assume you have already read [HED tagging strategy document](http://www.hedtags.org/downloads/HED%20Tagging%20Strategy%20Guide.pdf).

In general, you should use **Participant/Effect/** for things that mean something to the participant. You should search there to see if any combination of the existing tags could be used. 

For expected, there is **Participant/Effect/Cognitive/Expected** and you could use **Participant/Effect/Cognitive/Oddbal**l for the unexpected one.

**Comment by bigdelys** [comment]
@touryan should I close the issue?

**Comment by VisLab** [comment]
yes

**Comment by VisLab** [comment]
This has been addressed in HED-3G with the Task-property/Task-effect-evidence section of the hierarchy.
