### ISSUE TITLE
Make unit exponents clearer

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-specification#40]
Currently, unit exponents are concatenated onto the base unit without obvious separation (e.g. m2 for square meters/meters squared). It may be a good idea to separate the exponent from the base unit with a caret, making the aforementioned example m^2. This makes the nature of the exponent more obvious, and it would make it easier for the validator to split the unit and process the base and exponent separately. Think of meter^2 being pluralized as meters^2, or centi- (c-) being applied to the base of m^3 instead of the whole unit, as required in SI. We would have to explicitly allow carets in the specification in this use case, if they are not already permitted.

**Comment by happy5214** [comment]
This was fixed in #42.

**Comment by happy5214** [comment]
The carets were chopped off in the `unit` tags.

**Comment by VisLab** [comment]
Could you be more specific about where the problem is. Thanks....

**Comment by happy5214** [comment]
If you look at line 3643 of the v1.1.1-devunit XML file, you'll see that it has `m` instead of `m^2`. The other units with exponents are similarly sans caret.

**Comment by IanCa** [comment]
I added ^ to valid tag names(after discussing with Dr. Robbins) so they should be included now.

https://github.com/hed-standard/hed-python/commit/9a34d97adc4b2420db230d2ee9862ed35358bda6

**Comment by happy5214** [comment]
I see them now in the XML. This can now be closed.
