### ISSUE TITLE
Rename "Attribute/Sensory" to "Sensory-attribute"

### ISSUE THREAD

**Issue by MichaelJachan** [hed-standard/hed-specification#401]
It seems, the old string "Attribute/Sensory", which occurs in some <name>suggestedTag</name> - tags, shall be renamed to the new string "Sensory-attribute". 

THEN, my test case "All related and suggested terms do occur somewhere in the tree" would be fulfilled.

**Comment by VisLab** [comment]
Thanks for pointing that out. I will put a prelease version of the HED schema in a new prerelease directory in hed-specification. This version is not stable, but rather a working draft for release 8.0.1.

The test is also a good one for us to incorporate as a schema validation warning.  I have created a general [hed-standard/hed-python#349](https://github.com/hed-standard/hed-python#349) catch-all issue to gather suggestions
for future modifications of the schema validator.

**Comment by VisLab** [comment]
This has been corrected in the just released 8.1.0.
