### ISSUE TITLE
Adding amplitudeUnits to Unit classes

### ISSUE THREAD

**Issue by tpatpa** [hed-standard/hed-specification#436]
Identified the need for amplitude unit class when developing the HED schema library for SCORE.

See more: https://github.com/hed-standard/hed-schema-library/pull/15/files/76d98da0360ce7f07cbb56d92b0bd00cc8c57df4..be88a031b5895125bcd1392e8e2ca53de84d0e4b#r868114131

**Comment by VisLab** [comment]
An `electricPotentialUnitClass` with default units of microvolts was added in 8.1.0. This should be used as the amplitude units.
