### ISSUE TITLE
Global restructuring:  Sensory presentation subtree

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#44]
The basic categories are present.  The problem is that there are some odd things as you get deeper in (not shown).   For example:  Sensory presentation/Auditory/Click/ABR (Auditory brain stem response).  Another example is Sensory presentation/Visual/Rendering type.  Shouldn't Rendering type be a visual attribute?

**Sensory presentation**
* Auditory 
** Nameable 
** Cash register  
** Ding 
** Buzz 
** Fire alarm 
** Click 
** Tone 
** Siren 
** Music 
** Noise 
** Human voice 
** Animal voice 
** Real world 
** Nonverbal vocal 
** Nonvocal 

* Olfactory
* Taste 
* Tactile 
* Visual  
** Rendering type

**Comment by dungscout96** [comment]
While **Sensory presentation/Visual** subtree only has the rendering type (which I second that it should be an attribute) and no specific visual object, the **Auditory** subtree list specific sounds. 
Does it make sense to create a subtree *Sound* in Item/:
**Item**
* Sound
   * Alarm
   * Buzz
   * Click
   * Ding
   * Music
   * Siren
   * Tone

And also create a subtree Attribute/Sensory presentation which replace the current Attribute/Presentation:
* Attribute
   * Sensory presentation
      * Visual
      * Auditory
      * Fraction
      * Type
         * Background
         * Foreground

The currently proposed of the Attribute/Sensory presentation might need more organizing but that's the idea.

Some sounds can be replaced using group tag:
* Human voice --> (Item/Object/Person, Attribute/Sensory presentation/Auditory)
* Animal voice --> (Item/Object/Animal, Attribute/Sensory presentation/Auditory)
* Cash register --> (Item/Object/Cash register [which we can add to Item], Attribute/Sensory presentation/Auditory)
...

I'm not sure what to do with *Nonverbal vocal* and *Nonvocal* yet. Can someone give an example of their usage?

**Comment by VisLab** [comment]
The example of Nonvocal listed in the schema is a car engine or gears --- anything not made by human.  This fits into the same   (Item/Object/Vehicle, Attribute/Sensory presentation/Auditory) scheme.

Nonverbal  are things like Yawn, Gulp, Gurgle, Sneeze.    I think these should be under actions --- many of them already are:

(Action/Involuntary/Yawn, Attribute/Sensory presentation/Auditory)

I agree with Dung's suggestion to move Sensory presentation to an Attribute

**Comment by bigdelys** [comment]
I agree with Dung's suggestion too. Also agree that Rendering type should be a visual attribute.

**Comment by VisLab** [comment]
I am moving Sensory presentation to Attribute.  However,  I don't think Human voice is:
(Item/Object/Person, Attribute/Sensory presentation Auditory).

The sense in which it is used is that of presenting to a subject.  It is what the subject experiences.  I guess we need to clarify what that means in the comments.

**Comment by VisLab** [comment]
This has been completed in the current specification.
