### ISSUE TITLE
HED needs clearer definitions of coordinate systems

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#45]
Example:
Attribute/Location/Real-world coordinates/Room/xyz/#

is the only coordinate specification in HED.

**Comment by VisLab** [comment]
Attribute/Location/Reference frame also needs work.

**Comment by sappelhoff** [comment]
What kind of coordinate frames are you thinking about here?

- For rooms when doing motion tracking?
- For screens when referring to the point of focus during eyetracking?
- For digitized electrode positions on the scalp of participant during EEG recording?
- ...?

And how would you plan to handle the coordinate systems? For example in BIDS, there are "keywords" that can be used - such as `"CapTrak"`, which refers to a specific coordinate system that is defined in a separate documentation. These keywords can then be extended in pull requests, see e.g., https://github.com/sccn/bids-matlab-tools/issues/51

Would this be done similarly in HED, or are you thinking of another way?

**Comment by VisLab** [comment]
Yes, the coordinate systems mentioned above and many more --- for example specifying spatial characteristics on stimuli on a computer screen --- and then other things such as VR and AR need to be considered. There are also coordinate systems moving with relevant objects. 

The BIDS approach is problematic. There is not enough information in the specification to allow transformations among coordinate systems or even to correctly understand the relationship between various coordinate systems in a practical setting.  The eye-tracking and the motion-capture specs appear to be going their own ways, and there really isn't a unifying framework from the user's perspective. 

The HED-3G specification (section 3.7) has started on this, but we are no where near settling on the "right" solution.  I think there is one --- I just have no idea what it is yet. I'm trying to avoid making too many commitments in the HED-3G specification before things are clearer. Ideally, there would be enough information in the data for tool-builders to handle coordinate systems in a transparent manner.

**Comment by VisLab** [comment]
This will need to be addressed in a future library schema.  It appears that some BIDS modalities will have some specifications about coordinate systems (such as motion and eye tracking).  We will need to follow their lead in the future.
