### ISSUE TITLE
Reorganizing hed-specification repo

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#457]
In working on the HED documentation, I realized that we (i.e. I) made a strategic error in setting up the `hed-standard` repositories.  In particular, the HED specification should be in its own repo, and all of the schema should be in `hed-schema-library`. 

If we do this, it would consolidate schema development in one place.  It would also separate out the versioning of the specification from the versioning of the schema which is confusing now. Right now correcting the specification makes it look as though we are correcting the HED schema. People developing the library schemas would have the base schema right there.  Tools would not have to access two different repositories. The people interested in the specification are mostly tool developers, while the people interested in the schema are mostly annotators.

I realize that we will need to keep copies of the official hed schema on `hed-specification` for the indefinite future so that older versions of the tools will work. We can move the `prerelease` and all of the viewers to the `hed-schema-library` repo. 

Could you please give me thoughts and/or objections on doing this? @dungscout96 @smakeig @monique2208 @tpatpa @dorahermes @IanCa @happy5214 @sappelhoff @arnodelorme 

One question would be the directory structure for the `hed-schema-library` repo.

It could be:

```code
         docs
         library_schemas
         base_schema
```

or:

```code
        docs
        library_schemas
        hed_schema
```
or something else.

**Comment by dorahermes** [comment]
I think this makes a lot of sense for versioning, no preference on the directory structure naming.

**Comment by sappelhoff** [comment]
I agree with Dora on this.

**Comment by happy5214** [comment]
I prefer `standard_schema` for the schema currently stored in this repo. I've previously discussed with @VisLab the inevitable confusion surrounding using the term "base schema" for both the standard schema and a dataset's unprefixed schema, and suggested restricting that term's use to the latter.

**Comment by VisLab** [comment]
Agreed: `standard_schema` it is for the directory containing the these schema.

**Comment by VisLab** [comment]
This reorganization has been completed.
