### ISSUE TITLE
Revised Attribute syntax

### ISSUE THREAD

**Issue by smakeig** [hed-standard/hed-specification#47]
To me the frequent need for /Attribute/ tags is inefficient. I propose using curly braces to enclose allowed attributes

/Object/.../Circle {Color/green,Size/3.5 deg, Location, Screen Center}

This could make reading tags much easier, while not posing too heavy a burden on reprogramming of the HED validator (says Dung).

**Comment by smakeig** [comment]
My example should more accurately read

/Object/.../Circle {Color/green,Size/3.5 deg, Location/Screen Center}

**Comment by VisLab** [comment]
It is possible that we could do this --- but it would need to be in the devunit branch because we would have to rewrite the parser and validators for both the python and the javascript. Thus if we agreed on it, it would need to be implemented later after we have finished restructuring HED semantics.

However, since HED allows arbitrarily deep parentheses, why not just use parentheses?  What does introducing curly braces gain?

**Comment by dungscout96** [comment]
Not having to retyping and reading "Attribute" every time is a plus especially if a tag has many attributes. Another gain is that this make the relationship between tags and their modifiers in nested grouping situation utterly clear.

For example, a HED string describing a visual presentation of a moving bicycle in a 2D screen within a viewport using current syntax might look like this:

(Item/Object/Vehicle/Bicycle, Action/Move, Attribute/Color/Red, (Sensory presentation/Visual/Rendering type/Screen/2D, Attribute/Size/15 inches, Attribute/Location/Reference frame/Relative to participant/Distance/30 inches, (Sensory presentation/Visual/Rendering type/Screen/View port, Attribute/Size/10 inches)))

It's not clear (especially for machine) if the Sensory presentation tag groups describe the Action tag or the Item tag or even the Attribute tag (in this case we want to describe the Bicycle object). If we enforce the notation such that a modifying tag group must directly follow the modified tag then it would be hard (for human) to read the other modifying attributes:

(Item/Object/Vehicle/Bicycle, (Sensory presentation/Visual/Rendering type/Screen/2D, (Sensory presentation/Visual/Rendering type/Screen/View port, Attribute/Size/10 inches), Attribute/Size/15 inches, Attribute/Location/Reference frame/Relative to participant/Distance/30 inches), Action/Move, Attribute/Color/Red)

With curly brace notation it would read:

(Item/Object/Vehicle/Bicycle {Action/Move, Color/Red}, (Sensory presentation/Visual/Rendering type/Screen/2D {Size/15 inches, Location/Reference frame/Relative to participant/Distance/30 inches}, Sensory presentation/Visual/Rendering type/Screen/View port {Size/10 inches}))

Of course this assumes that we want to use nested grouping to explicitly state relationship between tags (and things they represent). As far as I know right now HED doesn't encourage nested grouping. This can be another discussion.

Now I have also included the Action/Move tag inside the curly brace while the original proposed use is only for Attribute tags. My thought is that it's also a modifier of the Bicycle object and for the validator it should be easy to check whether a tag in curly brace begins with a top-level prefix to determine if it's an Attribute/ tag.

But we agree that this can be done after we finished restructuring the schema.

**Comment by VisLab** [comment]
I think this curly brace scheme is clearer.   However, I think we need to wait until after the initial restructuring to do this.

**Comment by happy5214** [comment]
I also concur on delaying new syntax until after the schema restructuring is complete.

**Comment by VisLab** [comment]
After a preliminary implementation and doing examples, I believe this is not feasible.  Instead, we have gone to the unique mapping idea which is simpler and easier to use.
