### ISSUE TITLE
Add comment notation for HED

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-specification#48]
We should allow comments in HED tags. We suggest using the notation 
\# Comment ... \# 
We can write a verbose/smart print option to print out comment on separate line, or to print without comments.
-Scott & Dung

**Comment by VisLab** [comment]
Could you explain this a little more. I don't understand how it would be used and what wouldn't be covered by Event/Description as far as events go.

**Comment by happy5214** [comment]
I could see a possible use for comments that explain non-obvious tagging, which wouldn't really be a description of an event, but ideally all tagging should be obvious anyway.

**Comment by VisLab** [comment]
Comments should be included in the Description tag when tagging.  Comments in the schema are already there.
