### ISSUE TITLE
Clarify behavior of deprecated tag with children

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-specification#532]
When a tag with children is deprecated, its children need to be moved elsewhere.  Clarify this in the specification.

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-specification/pull/534
https://github.com/hed-standard/hed-python/pull/740

Adds validation for deprecatedFrom, among other things.

**Comment by VisLab** [comment]
This has been incorporated into the python schema validator.
