### ISSUE TITLE
Broken link in HED resources.

### ISSUE THREAD

**Issue by dorahermes** [hed-standard/hed-specification#557]
There is a broken link in the HED resources. In the section on [Creating a new library schema](https://www.hed-resources.org/en/latest/HowCanYouUseHed.html#creating-a-new-library-schema) in the following sentence:

"You should also read the [HED schema development guide](https://www.hed-resources.org/en/latest/HedSchemaDevelopmentGuide.html) to get an overview of the development process." 

The link to the HED schema development guide does not work.

**Comment by VisLab** [comment]
Fixed by PR [https://github.com/hed-standard/hed-examples/pull/336](https://github.com/hed-standard/hed-examples/pull/336)... Thx
