### ISSUE TITLE
PLACEHOLDER_INVALID for `Duration/#`

### ISSUE THREAD

**Issue by neuromechanist** [hed-standard/hed-specification#610]
I am trying to get the task duration from the Duration column:

```json
  "duration": {
    "Description": "Duration of the event, set typically to n/a. Instead, the duration of the event is determined by the onset/offset flags or the next event.",
    "Units": "seconds",
    "HED": {
      "duration": "Duration/#"
    }
  }

```

, but the HED description throws a placeholder error:
```shell
Column 'duration':
	hed string: Duration/#
		PLACEHOLDER_INVALID: There should be no # characters in a category sidecar string. Found 1
```

This seems to be at odds with the Duration and Delay definitions in the [specifications](https://hed-specification.readthedocs.io/en/latest/05_Advanced_annotation.html#using-duration:~:text=Notice%20that%20the,to%20each%20event.)

**Comment by VisLab** [comment]
You have the wrong level for the sidecar --- you are annotating duration as a category column.

The correct annotation is: 

```json
 "duration": {
    "Description": "Duration of the event, set typically to n/a....",
    "Units": "seconds",
    "HED": "Duration/#"
    }
  }

**Comment by neuromechanist** [comment]
Thanks, it makes sense now 🙌🏼
