### ISSUE TITLE
Modifying Sensory presentation/Auditory/Music items

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-specification#7]
Under Sensory presentation/Auditory/Music should also include Tone, Chord (instead of Chord sequence), and Genre, still keeping Vocal and Instrumental

**Comment by bigdelys** [comment]
Added Tone and Genre. I am not sure removing Chord sequence is a good idea... anyone else has an opinion?

**Comment by VisLab** [comment]
Detailed information about music will be left to library schema.  Hopefully a music community will develop.
